# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Las_File_Offline_001' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Las_File_Offline_001

  pod 'RealmSwift'
  
  pod 'Toast-Swift', '~> 5.0.1'

  pod 'SDWebImage'

  pod 'ZIPFoundation', '~> 0.9'


end



